language: java
sudo: false

jdk:
  - oraclejdk8

install: travis_wait mvn clean site --quiet -DbuildNumber=${TRAVIS_BUILD_NUMBER}

script: "mvn verify"

notifications:
  email:
    recipients:
     - eis@iki.fi
    on_success: change
    on_failure: always
    
after_failure:
  - cat target/surefire-reports/*.txt

after_success:
  - mvn clean cobertura:cobertura coveralls:report 
