language: java
sudo: false

jdk:
  - oraclejdk8

install: mvn clean site -DbuildNumber=${TRAVIS_BUILD_NUMBER}

script: "mvn verify"

notifications:
  email:
    recipients:
     - eis@iki.fi
    on_success: change
    on_failure: always